version: '3.3'
services:
  connector:
    ports:
      - 8080:8080
    image: docker.pkg.github.com/vagivagi/connector/connector:latest
    restart: always
    environment:
      INFO_MESSAGE: Hello World!
