version: '3.3'
services:
  connector:
    ports:
      - 8080:8080
    image: vagivagi/connector:latest
    restart: always
    environment:
      INFO_MESSAGE: Hello World!
      JAVA_OPTS : "-XX:ReservedCodeCacheSize=32M -Xss512k"
      BPL_JVM_THREAD_COUNT : 20
      BPL_JVM_HEAD_ROOM : 5
